res18_pre: 'runs/pre_train/resnet18.pth'
img_train: 'Data/Unseen/Img_Train.txt'
img_test: 'Data/Unseen/Img_Test.txt'
point_train: 'Data/Unseen/Point_Train.txt'
point_test: 'Data/Unseen/Point_Test.txt'
box_train: 'Data/Unseen/Box_Train.txt'
box_test: 'Data/Unseen/Box_Test.txt'
batch_size: 16
lr: 0.0001
Epoch: 80
Setting: 'Unseen'
num_heads: 4
emb_dim: 512
proj_dim: 512
N_p: 64
N_raw: 2048
num_affordance: 17
pairing_num: 2